### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by HMvdZijden** [astrandb/miele#442]
### The problem

Logger: homeassistant.setup
Source: setup.py:404
First occurred: 18:15:41 (1 occurrences)
Last logged: 18:15:41

Unable to prepare setup for platform 'miele.vacuum': Platform not found (cannot import name 'VacuumEntityDescription' from 'homeassistant.components.vacuum' (/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py)).

### Version of miele integration having the issue?

Panel info not exist

### Version of Home Assistant Core having the issue?

2024.2.3

### Anything in the logs that might be useful for us?

```txt
Zie boven.
```
Only a dishwasher, not a vacuum

### Additional information

Problem solved after update.

**Comment by bartkummel** [comment]
I get this error every time HA restarts. I only have a Miele Hob.

**Comment by astrandb** [comment]
This was fixed in version 2024.1.0 of the integration. Please make sure that you are fully updated.

**Comment by bartkummel** [comment]
It's not solved apparently: I have updated all my HACS stuff and HA itself as well, but still get this error. I just did a restart to confirm.

**Comment by astrandb** [comment]
What version of the Miele integration is loaded? You can se that if you open HACS and click Miele. In the upper left corner - above the colored release badge, you can se the downloaded version info.

**Comment by bartkummel** [comment]
It says `5049053`

**Comment by astrandb** [comment]
Thats odd, it is not a official release label. It is the tip of development 14-Nov-2023. It should say v2024.1.0. Please try redownload in HACS. Make sure that this latest version is selected when prompted. This problem is not related to the integration (in my opinion). HACS must have mixed something up as it is not informing you of available upgrade.

**Comment by bartkummel** [comment]
That fails, it tries to download from `https://github.com/astrandb/miele/releases/download/main/miele.zip`, but that doesn't exist.

**Comment by astrandb** [comment]
It should download `https://github.com/astrandb/miele/releases/download/v2024.1.0/miele.zip` and nothing else. Something is corrupt in your HACS.

**Comment by bartkummel** [comment]
Oh no! Thanks for pointing that out. I'll dive into it.
